from __future__ import annotations


SENTENCE_EXAMPLE_OVERRIDES: dict[str, tuple[str, str]] = {
    "的": ("这是我的书。", "This is my book."),
    "我": ("我今天很忙。", "I am busy today."),
    "你": ("你想喝水吗？", "Do you want to drink water?"),
    "是": ("他是我的朋友。", "He is my friend."),
    "了": ("我吃饱了。", "I am full."),
    "不": ("我不想去。", "I don't want to go."),
    "在": ("他在家。", "He is at home."),
    "他": ("他明天来。", "He will come tomorrow."),
    "我们": ("我们一起吃饭。", "Let's eat together."),
    "好": ("这个主意很好。", "This idea is good."),
    "有": ("我有一个问题。", "I have a question."),
    "这": ("这本书很好看。", "This book is interesting."),
    "就": ("我现在就走。", "I will leave right now."),
    "会": ("我会说中文。", "I can speak Chinese."),
    "吗": ("你好吗？", "How are you?"),
    "要": ("我要一杯水。", "I want a glass of water."),
    "什么": ("你在做什么？", "What are you doing?"),
    "说": ("请慢慢说。", "Please speak slowly."),
    "她": ("她是老师。", "She is a teacher."),
    "想": ("我想回家。", "I want to go home."),
    "一": ("我有一个朋友。", "I have a friend."),
    "很": ("今天很热。", "It is very hot today."),
    "知道": ("我知道这件事。", "I know about this matter."),
    "人": ("房间里有很多人。", "There are many people in the room."),
    "吧": ("我们走吧。", "Let's go."),
    "那": ("那是谁的包？", "Whose bag is that?"),
    "来": ("你明天来吗？", "Are you coming tomorrow?"),
    "都": ("我们都喜欢音乐。", "We all like music."),
    "个": ("给我一个苹果。", "Give me an apple."),
    "能": ("你能帮我吗？", "Can you help me?"),
    "去": ("我想去学校。", "I want to go to school."),
    "没": ("我没时间。", "I don't have time."),
    "和": ("我和他是朋友。", "He and I are friends."),
    "他们": ("他们在等你。", "They are waiting for you."),
    "到": ("我八点到公司。", "I arrive at the office at eight."),
    "对": ("你说得对。", "What you said is right."),
    "也": ("我也想去。", "I also want to go."),
    "啊": ("今天天气真好啊。", "The weather is really nice today."),
    "还": ("我还没吃饭。", "I haven't eaten yet."),
    "把": ("请把门关上。", "Please close the door."),
    "让": ("让我想一想。", "Let me think for a moment."),
    "做": ("你在做什么？", "What are you doing?"),
    "给": ("请给我一杯水。", "Please give me a glass of water."),
    "一个": ("我只要一个。", "I only want one."),
    "上": ("书在桌子上。", "The book is on the table."),
    "你们": ("你们准备好了吗？", "Are you all ready?"),
    "过": ("我去过北京。", "I have been to Beijing."),
    "没有": ("我今天没有课。", "I don't have class today."),
    "得": ("他跑得很快。", "He runs very fast."),
    "看": ("我想看电影。", "I want to watch a movie."),
    "真": ("这道菜真好吃。", "This dish is really tasty."),
    "着": ("门开着。", "The door is open."),
    "事": ("我有事要说。", "I have something to say."),
    "这个": ("这个问题很简单。", "This question is simple."),
    "怎么": ("你怎么知道？", "How do you know?"),
    "现在": ("现在几点了？", "What time is it now?"),
    "可以": ("现在可以走了。", "We can leave now."),
    "点": ("请快点回来。", "Please come back quickly."),
    "呢": ("你在找什么呢？", "What are you looking for?"),
    "如果": ("如果下雨，我就不去。", "If it rains, I won't go."),
    "只": ("我只想休息一下。", "I just want to rest for a bit."),
    "别": ("别担心。", "Don't worry."),
    "哦": ("哦，我明白了。", "Oh, I understand now."),
    "但": ("我想去，但没时间。", "I want to go, but I don't have time."),
    "被": ("我的手机被偷了。", "My phone was stolen."),
    "走": ("我们走吧。", "Let's go."),
    "太": ("今天太冷了。", "It is too cold today."),
    "这样": ("请不要这样做。", "Please don't do it like this."),
    "里": ("包里有钥匙。", "There are keys in the bag."),
    "跟": ("我跟你一起去。", "I will go with you."),
    "告诉": ("请告诉我真相。", "Please tell me the truth."),
    "因为": ("我迟到了，因为下雨了。", "I was late because it rained."),
    "自己": ("你要照顾自己。", "You need to take care of yourself."),
    "再": ("我们明天再说。", "Let's talk again tomorrow."),
    "听": ("我在听音乐。", "I am listening to music."),
    "这里": ("这里很安静。", "It is quiet here."),
    "快": ("请快点。", "Please hurry."),
    "谁": ("你在等谁？", "Who are you waiting for?"),
    "但是": ("我想买，但是太贵了。", "I want to buy it, but it is too expensive."),
    "多": ("这里人很多。", "There are many people here."),
    "用": ("我可以用你的笔吗？", "May I use your pen?"),
    "时候": ("你什么时候回来？", "When will you come back?"),
    "下": ("请坐下。", "Please sit down."),
    "已经": ("我已经吃过了。", "I have already eaten."),
    "谢谢": ("谢谢你的帮助。", "Thank you for your help."),
    "为什么": ("你为什么迟到？", "Why are you late?"),
    "觉得": ("我觉得有点冷。", "I feel a little cold."),
    "天": ("今天是星期天。", "Today is Sunday."),
    "像": ("她像她妈妈。", "She looks like her mother."),
    "这么": ("你怎么来得这么早？", "Why did you come so early?"),
    "它": ("它在桌子下面。", "It is under the table."),
    "从": ("我从学校回来了。", "I came back from school."),
    "先生": ("王先生在办公室。", "Mr. Wang is in the office."),
    "找": ("我在找钥匙。", "I am looking for my keys."),
    "最": ("这是我最喜欢的歌。", "This is my favorite song."),
    "喜欢": ("我喜欢喝茶。", "I like drinking tea."),
    "可": ("这可不容易。", "This really is not easy."),
    "为": ("你为什么笑？", "Why are you laughing?"),
    "大": ("这个房间很大。", "This room is big."),
    "可能": ("他可能不知道。", "He may not know."),
    "需要": ("我需要你的帮助。", "I need your help."),
    "是的": ("是的，我明白。", "Yes, I understand."),
    "死": ("那只鱼死了。", "That fish died."),
    "次": ("我下次再来。", "I will come again next time."),
    "出": ("太阳出来了。", "The sun came out."),
    "那么": ("不要那么紧张。", "Don't be so nervous."),
    "干": ("你在干什么？", "What are you doing?"),
    "那个": ("那个杯子是谁的？", "Whose cup is that?"),
    "嘿": ("嘿，你听我说。", "Hey, listen to me."),
    "们": ("你们明天来吗？", "Are you all coming tomorrow?"),
    "话": ("我有话想说。", "I have something to say."),
    "而": ("他年轻而有经验。", "He is young yet experienced."),
    "么": ("你想要什么？", "What do you want?"),
    "东西": ("我买了一些东西。", "I bought some things."),
    "应该": ("你应该早点休息。", "You should rest earlier."),
    "孩子": ("孩子在睡觉。", "The child is sleeping."),
    "起来": ("请站起来。", "Please stand up."),
    "所以": ("我累了，所以想休息。", "I am tired, so I want to rest."),
    "这些": ("这些书是新的。", "These books are new."),
    "才": ("我才知道这件事。", "I only just found out about this."),
    "两": ("我有两个问题。", "I have two questions."),
    "错": ("这个答案错了。", "This answer is wrong."),
    "还有": ("你还有问题吗？", "Do you have any more questions?"),
    "又": ("他又迟到了。", "He is late again."),
    "小": ("这个杯子太小了。", "This cup is too small."),
    "中": ("他在会议中。", "He is in a meeting."),
    "叫": ("你叫什么名字？", "What is your name?"),
    "嗯": ("嗯，我同意。", "Mm, I agree."),
    "该": ("我该走了。", "I should go."),
    "等": ("请等我一下。", "Please wait for me a moment."),
    "问题": ("这个问题不难。", "This question is not hard."),
    "一起": ("我们一起学习。", "We study together."),
    "拿": ("请拿一本书。", "Please take a book."),
    "更": ("今天比昨天更冷。", "Today is colder than yesterday."),
    "开始": ("会议马上开始。", "The meeting will start soon."),
    "帮": ("请帮我一下。", "Please help me for a moment."),
    "打": ("我想打电话。", "I want to make a phone call."),
    "爱": ("我爱我的家人。", "I love my family."),
    "带": ("别忘了带伞。", "Don't forget to bring an umbrella."),
    "时间": ("你有时间吗？", "Do you have time?"),
    "年": ("我明年毕业。", "I will graduate next year."),
    "请": ("请坐一下。", "Please sit for a moment."),
    "回": ("我马上回来。", "I will come back right away."),
    "工作": ("我今天工作很忙。", "Work is busy today."),
    "然后": ("我先吃饭，然后学习。", "I will eat first, then study."),
    "当": ("他当老师很多年了。", "He has been a teacher for many years."),
    "见": ("我很高兴见到你。", "I am glad to see you."),
    "钱": ("我没有带钱。", "I didn't bring money."),
    "噢": ("噢，原来是这样。", "Oh, so that's how it is."),
    "一样": ("我们的想法一样。", "Our ideas are the same."),
    "事情": ("事情已经解决了。", "The matter has already been settled."),
    "就是": ("这就是我的家。", "This is my home."),
    "吃": ("我想吃面条。", "I want to eat noodles."),
    "所有": ("所有人都来了。", "Everyone has arrived."),
    "开": ("请把窗户打开。", "Please open the window."),
    "一下": ("请等一下。", "Please wait a moment."),
    "家": ("我家离学校很近。", "My home is close to the school."),
    "非常": ("我非常喜欢这里。", "I like it here very much."),
    "看到": ("我看到他了。", "I saw him."),
    "希望": ("我希望你能来。", "I hope you can come."),
    "那些": ("那些花很漂亮。", "Those flowers are beautiful."),
    "哪": ("你要去哪？", "Where are you going?"),
    "当然": ("当然可以。", "Of course you can."),
    "也许": ("他也许会来。", "He may come."),
    "行": ("这样不行。", "This won't work."),
    "朋友": ("他是我的朋友。", "He is my friend."),
    "妈妈": ("妈妈正在做饭。", "Mom is cooking."),
    "相信": ("我相信你。", "I believe you."),
    "前": ("请往前走。", "Please walk forward."),
    "嗨": ("嗨，好久不见。", "Hi, long time no see."),
    "认为": ("我认为你说得对。", "I think you are right."),
    "将": ("他将参加会议。", "He will attend the meeting."),
    "这儿": ("这儿有座位。", "There is a seat here."),
    "今天": ("今天我很忙。", "I am busy today."),
    "明白": ("我明白你的意思。", "I understand what you mean."),
    "一直": ("他一直在等你。", "He has been waiting for you."),
    "看看": ("我想看看这个。", "I want to take a look at this."),
    "车": ("我的车在外面。", "My car is outside."),
    "时": ("我们三点时见。", "Let's meet at three o'clock."),
    "杀": ("不要杀那只鸡。", "Don't kill that chicken."),
    "地方": ("这个地方很安静。", "This place is quiet."),
    "不过": ("我想去，不过没时间。", "I want to go, but I don't have time."),
    "呃": ("呃，我还没想好。", "Uh, I haven't decided yet."),
    "发生": ("发生什么事了？", "What happened?"),
    "几": ("你有几个孩子？", "How many children do you have?"),
    "回来": ("他马上回来。", "He will come back right away."),
    "准备": ("我准备好了。", "I am ready."),
    "找到": ("我找到钥匙了。", "I found the keys."),
    "后": ("饭后我们散步。", "We take a walk after dinner."),
    "爸爸": ("爸爸在看报纸。", "Dad is reading the newspaper."),
    "一切": ("一切都会好的。", "Everything will be fine."),
    "抱歉": ("抱歉，我迟到了。", "Sorry, I'm late."),
    "比": ("他比我高。", "He is taller than me."),
    "感觉": ("我感觉好多了。", "I feel much better."),
    "些": ("我想买些水果。", "I want to buy some fruit."),
    "只是": ("我只是开玩笑。", "I was only joking."),
    "怎么样": ("你最近怎么样？", "How have you been recently?"),
    "出来": ("请出来一下。", "Please come out for a moment."),
    "不要": ("不要太担心。", "Don't worry too much."),
    "对不起": ("对不起，我来晚了。", "Sorry, I came late."),
    "问": ("我想问你一个问题。", "I want to ask you a question."),
    "离开": ("他明天离开北京。", "He leaves Beijing tomorrow."),
    "一点": ("我有一点累。", "I am a little tired."),
    "一定": ("我一定会来。", "I will definitely come."),
    "起": ("他每天六点起床。", "He gets up at six every day."),
    "还是": ("你喝茶还是咖啡？", "Do you drink tea or coffee?"),
    "发现": ("我发现一个问题。", "I found a problem."),
    "所": ("这是我所知道的。", "This is what I know."),
    "住": ("我住在上海。", "I live in Shanghai."),
    "件": ("我买了一件衣服。", "I bought a piece of clothing."),
    "正": ("现在正下雨。", "It is raining right now."),
    "而且": ("他聪明，而且很努力。", "He is smart and hardworking."),
    "并": ("我并不知道这件事。", "I do not actually know about this."),
    "必须": ("我必须马上走。", "I must leave right away."),
    "意思": ("这是什么意思？", "What does this mean?"),
    "放": ("请把书放在桌上。", "Please put the book on the table."),
    "不错": ("这个主意不错。", "This idea is pretty good."),
    "肯定": ("他肯定会同意。", "He will definitely agree."),
    "电话": ("我接了一个电话。", "I answered a phone call."),
    "为了": ("我为了家人努力工作。", "I work hard for my family."),
    "搞": ("你在搞什么？", "What are you doing?"),
    "棒": ("你做得很棒。", "You did a great job."),
    "第一": ("今天是第一天。", "Today is the first day."),
    "妈": ("我妈在家。", "My mom is at home."),
    "地": ("他慢慢地走。", "He walks slowly."),
    "进": ("请进来坐。", "Please come in and sit down."),
    "那样": ("不要那样说。", "Don't say it like that."),
    "大家": ("大家都准备好了。", "Everyone is ready."),
    "新": ("我买了新手机。", "I bought a new phone."),
    "您": ("您要喝茶吗？", "Would you like some tea?"),
    "向": ("他向老师问好。", "He greeted the teacher."),
    "一些": ("我买了一些水果。", "I bought some fruit."),
    "三": ("我有三本书。", "I have three books."),
    "那里": ("我在那里等你。", "I will wait for you there."),
    "以为": ("我以为你知道。", "I thought you knew."),
    "高兴": ("见到你我很高兴。", "I am happy to see you."),
    "嘛": ("这件事嘛，不难。", "As for this matter, it isn't hard."),
    "老": ("这栋楼很老。", "This building is very old."),
    "位": ("这位老师很有名。", "This teacher is famous."),
    "过来": ("请过来一下。", "Please come over for a moment."),
    "掉": ("我的钥匙掉了。", "My keys fell."),
    "先": ("你先走吧。", "You go first."),
    "等等": ("请等等我。", "Please wait for me."),
    "生活": ("我的生活很简单。", "My life is simple."),
    "之": ("这是意料之中的事。", "This is something that was expected."),
    "买": ("我想买一本书。", "I want to buy a book."),
    "种": ("这种菜很好吃。", "This kind of dish is tasty."),
    "医生": ("医生让我多休息。", "The doctor told me to rest more."),
    "最后": ("最后我们成功了。", "In the end, we succeeded."),
    "之前": ("吃饭之前要洗手。", "Wash your hands before eating."),
    "伙计": ("伙计，帮我一下。", "Buddy, help me for a moment."),
    "手": ("请洗手。", "Please wash your hands."),
    "任何": ("我没有任何问题。", "I don't have any questions."),
    "很多": ("这里有很多人。", "There are many people here."),
    "哪儿": ("你在哪儿？", "Where are you?"),
    "这种": ("我不喜欢这种味道。", "I don't like this kind of taste."),
    "上帝": ("感谢上帝。", "Thank God."),
    "女人": ("那个女人是医生。", "That woman is a doctor."),
    "名字": ("你的名字怎么写？", "How do you write your name?"),
    "认识": ("我认识他。", "I know him."),
    "坐": ("请坐这里。", "Please sit here."),
    "今晚": ("今晚我们一起吃饭。", "We will eat together tonight."),
    "其他": ("还有其他办法吗？", "Are there any other ways?"),
    "喝": ("我想喝水。", "I want to drink water."),
    "记得": ("请记得关门。", "Please remember to close the door."),
    "家伙": ("那个家伙很有意思。", "That guy is interesting."),
    "与": ("我想与你谈谈。", "I want to talk with you."),
    "或者": ("你可以坐车或者走路。", "You can take a car or walk."),
    "写": ("请写你的名字。", "Please write your name."),
    "穿": ("今天穿什么？", "What are you wearing today?"),
    "弄": ("我把衣服弄脏了。", "I got the clothes dirty."),
    "过去": ("过去的事别想了。", "Don't think about the past."),
    "哪里": ("你住在哪里？", "Where do you live?"),
    "啦": ("好啦，我知道了。", "All right, I know."),
    "却": ("他很累，却没有休息。", "He was tired, but he did not rest."),
    "算": ("这不算贵。", "This doesn't count as expensive."),
    "担心": ("别担心我。", "Don't worry about me."),
    "继续": ("我们继续工作吧。", "Let's keep working."),
    "送": ("我送你回家。", "I will take you home."),
    "女孩": ("那个女孩很聪明。", "That girl is smart."),
    "以": ("我以为你不来了。", "I thought you weren't coming."),
    "玩": ("孩子们在外面玩。", "The children are playing outside."),
    "亲爱": ("亲爱的，早点休息。", "Dear, get some rest early."),
    "下来": ("请坐下来。", "Please sit down."),
    "成": ("这件事成了。", "This worked out."),
    "条": ("我买了一条裤子。", "I bought a pair of pants."),
    "够": ("钱够了吗？", "Is there enough money?"),
    "父亲": ("我的父亲很忙。", "My father is busy."),
    "以前": ("我以前住在北京。", "I used to live in Beijing."),
    "跑": ("他每天早上跑步。", "He runs every morning."),
    "月": ("下个月见。", "See you next month."),
    "早": ("你今天来得很早。", "You came very early today."),
    "美国": ("他来自美国。", "He comes from the United States."),
    "长": ("这条路很长。", "This road is long."),
    "完全": ("我完全同意。", "I completely agree."),
    "宝贝": ("宝贝，快睡吧。", "Baby, go to sleep."),
    "号": ("我的房间号是三零二。", "My room number is 302."),
    "枪": ("警察有一把枪。", "The police officer has a gun."),
    "狗": ("那只狗很可爱。", "That dog is cute."),
    "可是": ("我想去，可是没时间。", "I want to go, but I don't have time."),
    "世界": ("世界很大。", "The world is big."),
    "小时": ("我等了一个小时。", "I waited for one hour."),
    "重要": ("这件事很重要。", "This matter is important."),
    "谈": ("我想和你谈谈。", "I want to talk with you."),
    "别人": ("不要拿别人的东西。", "Don't take other people's things."),
    "男人": ("那个男人是老师。", "That man is a teacher."),
    "头": ("我的头有点疼。", "My head hurts a little."),
    "机会": ("这是个好机会。", "This is a good opportunity."),
    "岁": ("我今年二十岁。", "I am twenty years old."),
    "出去": ("我想出去走走。", "I want to go out for a walk."),
    "活": ("他还活着。", "He is still alive."),
    "看见": ("我看见你了。", "I saw you."),
    "者": ("这里欢迎读者留言。", "Readers are welcome to leave comments here."),
    "打电话": ("我晚上给你打电话。", "I will call you tonight."),
    "喂": ("喂，你听得到吗？", "Hello, can you hear me?"),
    "好像": ("他好像不太高兴。", "He doesn't seem very happy."),
    "得到": ("我得到了一个机会。", "I got an opportunity."),
    "警察": ("警察来了。", "The police are here."),
    "完": ("我作业写完了。", "I finished my homework."),
    "张": ("我买了三张票。", "I bought three tickets."),
    "儿子": ("我儿子今年五岁。", "My son is five years old this year."),
    "之后": ("下课之后我们吃饭。", "We will eat after class."),
    "漂亮": ("这件衣服很漂亮。", "This piece of clothing is beautiful."),
    "分钟": ("请等五分钟。", "Please wait five minutes."),
    "接": ("请接电话。", "Please answer the phone."),
    "场": ("这场比赛很精彩。", "This match is exciting."),
    "再见": ("我们明天再见。", "See you tomorrow."),
    "求": ("我求你帮帮我。", "I beg you to help me."),
    "刚": ("我刚到家。", "I just got home."),
    "如何": ("你感觉如何？", "How do you feel?"),
    "比赛": ("我们赢了比赛。", "We won the match."),
    "呀": ("你终于来了呀。", "You finally came."),
    "情况": ("情况有点复杂。", "The situation is a bit complicated."),
    "变": ("天气变冷了。", "The weather has become cold."),
    "关系": ("这件事和我有关系。", "This matter has something to do with me."),
    "真是": ("今天真是太热了。", "Today is really too hot."),
    "女士": ("那位女士很有礼貌。", "That lady is polite."),
    "本": ("我买了两本书。", "I bought two books."),
    "马上": ("我马上回来。", "I will come back right away."),
    "决定": ("我决定留下来。", "I decided to stay."),
    "见到": ("很高兴见到你。", "Nice to meet you."),
    "根本": ("我根本不知道。", "I don't know at all."),
    "关于": ("我想问关于工作的事。", "I want to ask about work."),
    "那儿": ("我在那儿等你。", "I will wait for you there."),
    "难": ("这个问题很难。", "This question is hard."),
    "只要": ("只要努力，就会进步。", "As long as you work hard, you will improve."),
    "里面": ("包里面有钱。", "There is money inside the bag."),
    "每": ("我每天喝咖啡。", "I drink coffee every day."),
    "份": ("请给我一份菜单。", "Please give me a menu."),
    "到底": ("你到底想说什么？", "What exactly do you want to say?"),
    "了解": ("我很了解他。", "I know him very well."),
    "明天": ("明天我不上班。", "I don't work tomorrow."),
    "站": ("他站在门口。", "He is standing at the door."),
    "结束": ("会议结束了。", "The meeting is over."),
    "公司": ("他在一家公司工作。", "He works at a company."),
    "成为": ("我想成为医生。", "I want to become a doctor."),
    "永远": ("我永远不会忘记你。", "I will never forget you."),
    "帮助": ("谢谢你的帮助。", "Thank you for your help."),
    "来说": ("对我来说，这很重要。", "To me, this is important."),
    "多少": ("这个多少钱？", "How much is this?"),
    "哇": ("哇，这里真漂亮！", "Wow, it is really beautiful here!"),
    "名": ("他是一名医生。", "He is a doctor."),
    "它们": ("它们都很新。", "They are all new."),
    "总": ("他总是很忙。", "He is always busy."),
    "确定": ("你确定吗？", "Are you sure?"),
    "有人": ("外面有人在等你。", "Someone is waiting for you outside."),
    "清楚": ("请说清楚一点。", "Please say it more clearly."),
    "晚上": ("晚上我们在家吃饭。", "We will eat at home tonight."),
    "安全": ("这里很安全。", "It is safe here."),
    "怎样": ("你想怎样做？", "How do you want to do it?"),
    "没什么": ("没什么大问题。", "There is no big problem."),
    "块": ("这块蛋糕很好吃。", "This piece of cake is tasty."),
    "回家": ("我想早点回家。", "I want to go home early."),
    "留": ("请留在这里。", "Please stay here."),
    "周": ("我们下周见。", "We will meet next week."),
    "愿意": ("你愿意帮我吗？", "Are you willing to help me?"),
    "计划": ("你的计划是什么？", "What is your plan?"),
    "爸": ("我爸今天休息。", "My dad has the day off today."),
    "俩": ("我们俩一起去。", "The two of us will go together."),
    "停": ("车停在门口。", "The car is parked at the door."),
    "不能": ("我今天不能去。", "I can't go today."),
    "他妈的": ("他妈的，我忘带钥匙了。", "Damn it, I forgot my keys."),
    "说话": ("请小声说话。", "Please speak quietly."),
    "另": ("我另有安排。", "I have other plans."),
    "心": ("他心里很难过。", "He feels very sad."),
    "花": ("我买了一束花。", "I bought a bunch of flowers."),
    "她们": ("她们都是学生。", "They are all students."),
    "有些": ("有些人喜欢早起。", "Some people like getting up early."),
    "门": ("请把门关上。", "Please close the door."),
    "感谢": ("感谢你的帮助。", "Thank you for your help."),
    "谈谈": ("我想和你谈谈。", "I want to talk with you."),
    "定": ("时间定了吗？", "Has the time been set?"),
    "于": ("他出生于上海。", "He was born in Shanghai."),
    "以后": ("以后再说吧。", "Let's talk about it later."),
    "管": ("这件事归他管。", "He is in charge of this matter."),
    "照片": ("这张照片很清楚。", "This photo is clear."),
    "每个": ("每个人都很忙。", "Everyone is busy."),
    "欢迎": ("欢迎来到北京。", "Welcome to Beijing."),
    "敢": ("我不敢一个人去。", "I don't dare to go alone."),
    "兄弟": ("他有两个兄弟。", "He has two brothers."),
    "从来": ("我从来没去过那里。", "I have never been there."),
    "总是": ("他总是迟到。", "He is always late."),
    "嘴": ("请闭上嘴。", "Please close your mouth."),
    "跳": ("她跳得很高。", "She jumps very high."),
    "拜托": ("拜托你帮我一下。", "Please help me out."),
    "女儿": ("我的女儿在上学。", "My daughter is in school."),
    "抓": ("他抓住了我的手。", "He grabbed my hand."),
    "小姐": ("小姐，请问洗手间在哪？", "Miss, where is the restroom?"),
    "动": ("别动我的电脑。", "Don't touch my computer."),
    "赢": ("我们赢了比赛。", "We won the match."),
    "消息": ("我有一个好消息。", "I have good news."),
    "女": ("她是女医生。", "She is a female doctor."),
    "忙": ("我今天很忙。", "I am busy today."),
    "或许": ("他或许知道答案。", "He might know the answer."),
    "如此": ("事情就是如此简单。", "It is just that simple."),
    "队": ("请在这里排队。", "Please line up here."),
    "无法": ("我无法回答这个问题。", "I can't answer this question."),
    "房子": ("这房子很大。", "This house is big."),
    "拉": ("请把门拉开。", "Please pull the door open."),
    "衣服": ("我买了新衣服。", "I bought new clothes."),
    "听说": ("听说你要搬家。", "I heard you are moving."),
    "救": ("请救救我。", "Please save me."),
    "参加": ("我想参加这个活动。", "I want to join this event."),
    "办法": ("我有一个办法。", "I have a way."),
    "睡": ("我想早点睡。", "I want to sleep early."),
    "唯一": ("这是唯一的办法。", "This is the only way."),
    "回去": ("我们现在回去吧。", "Let's go back now."),
    "人们": ("人们都喜欢和平。", "People all like peace."),
    "晚": ("今天有点晚了。", "It is a bit late today."),
    "该死": ("该死，我迟到了。", "Damn it, I'm late."),
    "闭": ("请闭上眼睛。", "Please close your eyes."),
    "选择": ("你可以自己选择。", "You can choose for yourself."),
    "坏": ("我的手机坏了。", "My phone is broken."),
    "原因": ("这就是原因。", "This is the reason."),
    "下去": ("请继续说下去。", "Please keep talking."),
    "受": ("他受了伤。", "He was injured."),
    "连": ("我连名字都忘了。", "I even forgot the name."),
    "好好": ("你要好好休息。", "You need to rest well."),
    "全": ("全班都来了。", "The whole class came."),
    "确实": ("这确实很难。", "This is indeed hard."),
    "挺": ("这里挺安静的。", "It is pretty quiet here."),
    "此": ("此事以后再说。", "We will discuss this matter later."),
    "水": ("我想喝水。", "I want to drink water."),
    "混蛋": ("别叫他混蛋。", "Don't call him a jerk."),
    "杯": ("我想要一杯茶。", "I want a cup of tea."),
    "保证": ("我保证不迟到。", "I promise I won't be late."),
    "学校": ("学校离我家很近。", "The school is close to my home."),
    "卖": ("这家店卖水果。", "This store sells fruit."),
    "信": ("我收到你的信了。", "I received your letter."),
    "接受": ("我接受你的建议。", "I accept your suggestion."),
    "改变": ("天气改变了计划。", "The weather changed the plan."),
    "舞": ("她喜欢跳舞。", "She likes dancing."),
    "看来": ("看来要下雨了。", "It looks like it is going to rain."),
    "高": ("这座楼很高。", "This building is tall."),
    "麻烦": ("这件事有点麻烦。", "This matter is a bit troublesome."),
    "出现": ("他突然出现了。", "He suddenly appeared."),
    "打算": ("你打算什么时候走？", "When do you plan to leave?"),
    "电影": ("我想看电影。", "I want to watch a movie."),
    "试": ("我想试一下。", "I want to try it."),
    "身上": ("我身上没有现金。", "I don't have cash on me."),
    "房间": ("房间里很安静。", "It is quiet in the room."),
    "美": ("这里的风景很美。", "The scenery here is beautiful."),
    "不管": ("不管怎样，我都会去。", "No matter what, I will go."),
    "书": ("这本书很有意思。", "This book is interesting."),
    "特别": ("今天特别冷。", "It is especially cold today."),
    "注意": ("请注意安全。", "Please pay attention to safety."),
    "球": ("他喜欢打球。", "He likes playing ball."),
    "查": ("请查一下时间。", "Please check the time."),
    "忘": ("我忘了他的名字。", "I forgot his name."),
    "甚至": ("他甚至没有道歉。", "He didn't even apologize."),
    "保护": ("我们要保护环境。", "We need to protect the environment."),
    "真正": ("这才是真正的问题。", "This is the real problem."),
    "结果": ("结果很好。", "The result is good."),
    "表现": ("他今天表现很好。", "He performed well today."),
    "拍": ("我想拍一张照片。", "I want to take a photo."),
    "其实": ("其实我不太懂。", "Actually, I don't really understand."),
    "小心": ("路上小心。", "Be careful on the road."),
    "进来": ("你可以进来。", "You may come in."),
    "路": ("这条路很长。", "This road is long."),
    "呆": ("我在家呆了一天。", "I stayed at home for a day."),
    "四": ("我有四个苹果。", "I have four apples."),
    "久": ("我等了很久。", "I waited for a long time."),
    "当时": ("当时我很紧张。", "I was nervous at the time."),
    "或": ("请打电话或发邮件。", "Please call or send an email."),
    "懂": ("我懂你的意思。", "I understand what you mean."),
    "只有": ("我只有一个问题。", "I only have one question."),
    "怎么办": ("我该怎么办？", "What should I do?"),
    "第": ("这是第一课。", "This is the first lesson."),
    "马": ("那匹马跑得很快。", "That horse runs fast."),
    "讲": ("请讲慢一点。", "Please speak a little more slowly."),
    "绝对": ("我绝对同意。", "I absolutely agree."),
    "长官": ("长官，请听我解释。", "Sir, please listen to my explanation."),
    "员": ("他是公司职员。", "He is an office worker."),
    "进去": ("我可以进去吗？", "May I go in?"),
    "至少": ("我至少需要一天。", "I need at least one day."),
    "律师": ("她是一名律师。", "She is a lawyer."),
    "喔": ("喔，我想起来了。", "Oh, I remember now."),
    "整个": ("我整个下午都在学习。", "I studied all afternoon."),
    "听到": ("你听到声音了吗？", "Did you hear the sound?"),
    "表演": ("她的表演很好。", "Her performance was good."),
    "趴下": ("请趴下别动。", "Please lie down and don't move."),
    "退后": ("请退后一点。", "Please step back a little."),
    "拜拜": ("拜拜，明天见。", "Bye, see you tomorrow."),
    "蠢货": ("别叫他蠢货。", "Don't call him an idiot."),
    "选": ("我想选这个。", "I want to choose this one."),
    "远": ("这里离家很远。", "This place is far from home."),
    "儿": ("我有一个儿子。", "I have a son."),
    "处理": ("我来处理这件事。", "I will handle this matter."),
    "是否": ("他问我是否有空。", "He asked whether I was free."),
    "段": ("每人读一段。", "Each person reads one paragraph."),
    "令": ("这个消息令人遗憾。", "This news is regrettable."),
    "酒": ("这里卖红酒吗？", "Do they sell red wine here?"),
    "调查": ("请调查一下这件事。", "Please investigate this matter."),
    "歌": ("我喜欢这首歌。", "I like this song."),
    "之间": ("他藏在两辆车之间。", "He hid between two cars."),
    "探": ("他探头看了一眼。", "He poked his head out and looked."),
    "万": ("这里有一万人。", "There are ten thousand people here."),
    "派": ("他们派我去北京。", "They sent me to Beijing."),
    "有点": ("我有点累。", "I am a little tired."),
    "靠": ("别靠太近。", "Don't stand too close."),
    "解决": ("我们解决了问题。", "We solved the problem."),
    "作为": ("作为朋友，我支持你。", "As a friend, I support you."),
    "奇怪": ("这件事很奇怪。", "This matter is strange."),
    "由": ("这件事由我负责。", "I am responsible for this matter."),
    "男": ("他是男孩子。", "He is a boy."),
    "危险": ("这里很危险。", "It is dangerous here."),
    "国家": ("中国是一个大国家。", "China is a large country."),
    "控制": ("请控制车速。", "Please control your speed."),
    "最近": ("你最近怎么样？", "How have you been lately?"),
    "声音": ("什么声音？", "What sound is that?"),
    "糟": ("情况很糟。", "The situation is bad."),
    "快乐": ("她很快乐。", "She is happy."),
    "可爱": ("这只猫很可爱。", "This cat is cute."),
    "进入": ("请进入房间。", "Please enter the room."),
    "事实上": ("事实上，她撒谎了。", "In fact, she lied."),
    "哈": ("哈哈，我赢了。", "Haha, I won."),
    "醒": ("我醒了。", "I woke up."),
    "分": ("把蛋糕分给大家。", "Share the cake with everyone."),
    "部": ("这部电影很好看。", "This movie is good."),
    "同": ("我们同一天到达。", "We arrived on the same day."),
    "样子": ("我喜欢你笑的样子。", "I like the way you smile."),
    "少": ("今天人很少。", "There are few people today."),
    "有趣": ("这个故事很有趣。", "This story is interesting."),
    "提": ("请提一个问题。", "Please ask a question."),
    "除了": ("除了你，大家都来了。", "Everyone came except you."),
    "保持": ("请保持安静。", "Please keep quiet."),
    "办": ("这件事我来办。", "I will take care of this matter."),
    "教": ("她教我中文。", "She teaches me Chinese."),
    "加": ("请加一点糖。", "Please add a little sugar."),
    "简单": ("这个问题很简单。", "This question is simple."),
    "恩": ("他对我有恩。", "He has done me a kindness."),
    "曾": ("我曾去过北京。", "I once went to Beijing."),
    "飞机": ("飞机快到了。", "The plane is arriving soon."),
    "家庭": ("我爱我的家庭。", "I love my family."),
    "象": ("动物园有一头大象。", "There is an elephant at the zoo."),
    "装": ("请把书装进包里。", "Please put the book into the bag."),
    "玩笑": ("这只是一个玩笑。", "This is just a joke."),
    "使": ("这件事使我高兴。", "This matter makes me happy."),
    "博士": ("他是医学博士。", "He is a doctor of medicine."),
    "直到": ("我会等到下周。", "I will wait until next week."),
    "二": ("我有两个苹果。", "I have two apples."),
    "小子": ("那个小子很聪明。", "That boy is clever."),
    "不好意思": ("真不好意思。", "I am really sorry."),
    "的确": ("你的确说得对。", "You are indeed right."),
    "特": ("她很特别。", "She is special."),
    "怪": ("这个问题很怪。", "This question is odd."),
    "美元": ("这本书四美元。", "This book is four dollars."),
    "瞧": ("你瞧，这是什么？", "Look, what is this?"),
    "疯狂": ("这个想法很疯狂。", "This idea is crazy."),
    "收到": ("我收到了你的信。", "I received your letter."),
    "其中": ("其中一个是我的。", "One of them is mine."),
    "黑": ("天快黑了。", "It is getting dark."),
    "作": ("这是我的作品。", "This is my work."),
    "性": ("每个人的性格不同。", "Everyone has a different personality."),
    "昨天": ("我昨天见了他。", "I saw him yesterday."),
    "抓住": ("请抓住我的手。", "Please hold my hand."),
    "越": ("不要越过这条线。", "Do not cross this line."),
    "怕": ("我怕黑。", "I am afraid of the dark."),
    "多久": ("你等了多久？", "How long did you wait?"),
    "直接": ("请直接回家。", "Please go straight home."),
    "对于": ("对于这个问题，我没有意见。", "As for this question, I have no opinion."),
    "记": ("请记住我的话。", "Please remember what I said."),
    "除非": ("除非你同意，否则我不去。", "Unless you agree, I won't go."),
    "酷": ("这个主意很酷。", "This idea is cool."),
    "终于": ("雨终于停了。", "The rain finally stopped."),
    "步": ("他让步了。", "He gave in."),
    "方法": ("这个方法很好。", "This method is good."),
    "犯": ("他犯了一个错误。", "He made a mistake."),
    "扔": ("把它扔掉。", "Throw it away."),
    "能力": ("她有学习语言的能力。", "She has the ability to learn languages."),
    "克": ("这袋糖重五克。", "This bag of sugar weighs five grams."),
    "耶": ("耶，我赢了！", "Yay, I won!"),
    "日": ("今天是星期日。", "Today is Sunday."),
    "有关": ("这件事和你有关。", "This matter has to do with you."),
    "另外": ("另外，我还有一个问题。", "Besides, I have one more question."),
    "丢": ("我把钥匙丢了。", "I lost my keys."),
    "回答": ("请回答我的问题。", "Please answer my question."),
    "命": ("他救了我的命。", "He saved my life."),
    "梦": ("我做了一个梦。", "I had a dream."),
    "试试": ("你可以试试。", "You can give it a try."),
    "那天": ("那天我在家。", "I was at home that day."),
    "滚": ("球滚到门口。", "The ball rolled to the door."),
    "戴": ("我戴着手表。", "I am wearing a watch."),
    "子": ("我有一个儿子。", "I have a son."),
    "藏": ("他把书藏起来了。", "He hid the book."),
    "底": ("箱子底下有书。", "There are books under the box."),
    "报告": ("请写一份报告。", "Please write a report."),
    "替": ("我替你去。", "I will go for you."),
    "面": ("我想吃面。", "I want to eat noodles."),
    "经历": ("我经历过很多困难。", "I have gone through many difficulties."),
    "飞": ("鸟在天上飞。", "The bird is flying in the sky."),
    "气": ("轮胎没气了。", "The tire has no air."),
    "套": ("这套衣服很好看。", "This outfit looks good."),
    "屁股": ("他坐在地上，屁股很疼。", "He sat on the ground, and his bottom hurt."),
    "生日": ("今天是我的生日。", "Today is my birthday."),
    "线": ("请画一条线。", "Please draw a line."),
    "光": ("阳光很强。", "The sunlight is strong."),
    "神": ("他们相信神。", "They believe in God."),
    "操": ("请小心操作。", "Please operate it carefully."),
    "姑娘": ("那个姑娘很漂亮。", "That girl is pretty."),
    "道": ("这是一条小道。", "This is a small path."),
    "钥匙": ("请带钥匙来。", "Please bring the key."),
    "包": ("请把书包起来。", "Please wrap the book up."),
    "腿": ("我的腿疼。", "My leg hurts."),
    "自": ("请自我介绍一下。", "Please introduce yourself."),
    "整": ("我看了完整版。", "I watched the full version."),
    "投票": ("请给我投票。", "Please vote for me."),
    "手术": ("手术很成功。", "The surgery was successful."),
    "身边": ("她坐在我身边。", "She sat beside me."),
    "痛苦": ("他经历了很多痛苦。", "He went through a lot of pain."),
    "全部": ("全部都到了。", "Everyone has arrived."),
    "组": ("我们分成三组。", "We split into three groups."),
    "交": ("我想交朋友。", "I want to make friends."),
    "以及": ("他买了书以及笔。", "He bought books and pens."),
    "台": ("我买了一台电脑。", "I bought a computer."),
    "显然": ("显然，你错了。", "Clearly, you are wrong."),
    "局": ("这个局面很复杂。", "This situation is complicated."),
    "火": ("火很大。", "The fire is big."),
    "猫": ("那只猫很可怜。", "That cat is pitiful."),
    "即使": ("即使下雨，我也要去。", "Even if it rains, I will go."),
    "卡": ("我的卡丢了。", "I lost my card."),
    "洗": ("饭前要洗手。", "Wash your hands before meals."),
    "混": ("请把它们混在一起。", "Please mix them together."),
    "挂": ("请把衣服挂起来。", "Please hang up the clothes."),
    "未来": ("未来会更好。", "The future will be better."),
    "道歉": ("我向他道歉了。", "I apologized to him."),
    "案": ("这个案子很复杂。", "This case is complicated."),
    "根": ("这棵树的根很深。", "This tree's roots are deep."),
    "吓": ("他吓了我一跳。", "He gave me a fright."),
    "边": ("杯子在桌边。", "The cup is at the edge of the table."),
    "城市": ("这个城市很大。", "This city is big."),
    "合作": ("我们需要合作。", "We need to cooperate."),
    "来到": ("他来到北京。", "He came to Beijing."),
    "乱": ("别乱动。", "Don't move around."),
    "词": ("这个词很常用。", "This word is commonly used."),
    "尔": ("我偶尔做饭。", "I cook occasionally."),
    "超": ("价格超过一百元。", "The price is over one hundred yuan."),
    "老婆": ("我老婆在家。", "My wife is at home."),
    "同性恋": ("他是同性恋。", "He is gay."),
    "面前": ("他在我面前道歉了。", "He apologized in front of me."),
    "位置": ("请保留我的位置。", "Please save my seat."),
    "收": ("请把书收起来。", "Please put the books away."),
    "电脑": ("请打开电脑。", "Please turn on the computer."),
    "区": ("我住在这个区。", "I live in this district."),
    "似乎": ("这似乎很便宜。", "This seems cheap."),
    "感": ("我感觉很好。", "I feel good."),
    "杀死": ("这药能杀死细菌。", "This medicine can kill bacteria."),
    "其": ("它有其优点。", "It has its advantages."),
    "脱": ("请脱下外套。", "Please take off your coat."),
    "法律": ("法律面前人人平等。", "Everyone is equal before the law."),
    "训练": ("每天训练很重要。", "Training every day is important."),
    "米": ("我买了一袋米。", "I bought a bag of rice."),
    "阿": ("阿姨在家。", "Auntie is at home."),
    "主": ("他是这家店的主人。", "He is the owner of this store."),
    "使用": ("我每天使用电脑。", "I use a computer every day."),
    "证明": ("你能证明吗？", "Can you prove it?"),
    "法": ("这个办法很好。", "This method is good."),
    "睡觉": ("我要睡觉了。", "I want to sleep."),
    "干什么": ("你在干什么？", "What are you doing?"),
    "见面": ("我们在哪儿见面？", "Where shall we meet?"),
    "战争": ("没人喜欢战争。", "No one likes war."),
    "杀人": ("杀人是犯罪。", "Killing is a crime."),
    "不同": ("这两个方法不同。", "These two methods are different."),
    "傻": ("他不傻。", "He is not dumb."),
    "关心": ("我很关心你。", "I care about you."),
    "毁": ("这场雨毁了计划。", "This rain ruined the plan."),
    "晚安": ("晚安，明天见。", "Good night, see you tomorrow."),
    "白痴": ("别叫他白痴。", "Don't call him an idiot."),
    "中心": ("我住在城市中心。", "I live in the city center."),
    "妹妹": ("我没有妹妹。", "I don't have a younger sister."),
    "输": ("我们输了。", "We lost."),
    "尽": ("我已经尽力了。", "I have already done my best."),
    "赶": ("我赶时间。", "I am in a hurry."),
    "人生": ("人生很短。", "Life is short."),
    "算是": ("这算是一个好办法。", "This counts as a good method."),
    "大人": ("他已经是大人了。", "He is already an adult."),
    "再次": ("请再次确认。", "Please confirm it again."),
    "醉": ("他喝醉了。", "He got drunk."),
    "某": ("某人打电话给你。", "Someone called you."),
    "自从": ("自从那天以后，我很少见他。", "Since that day, I rarely see him."),
    "演出": ("今晚有演出。", "There is a show tonight."),
    "超级": ("这部电影超级好看。", "This movie is really good."),
    "累": ("我累坏了。", "I am exhausted."),
    "样": ("这个样子很好看。", "This style looks good."),
    "取": ("我去取包裹。", "I am going to pick up the package."),
    "受害者": ("受害者需要帮助。", "The victim needs help."),
    "联邦": ("这是一个联邦国家。", "This is a federal country."),
    "造成": ("大雨造成了堵车。", "The heavy rain caused a traffic jam."),
    "抱": ("请抱一下孩子。", "Please hold the child."),
    "班": ("我今天上班。", "I am working today."),
    "名单": ("你的名字在名单上。", "Your name is on the list."),
    "嘘": ("他在吹嘘自己。", "He is bragging about himself."),
    "将军": ("将军下了命令。", "The general gave an order."),
    "惊喜": ("这是一个惊喜。", "This is a surprise."),
    "拿走": ("请把垃圾拿走。", "Please take the trash away."),
    "酒店": ("酒店离车站很近。", "The hotel is close to the station."),
    "从未": ("我从未去过那里。", "I have never been there."),
    "帐": ("我们搭了一个帐篷。", "We put up a tent."),
    "不少": ("这里人不少。", "There are quite a few people here."),
    "战": ("战争结束了。", "The war ended."),
    "亚": ("亚洲很大。", "Asia is large."),
    "取消": ("会议取消了。", "The meeting was canceled."),
    "庆祝": ("我们庆祝生日。", "We celebrate birthdays."),
    "想起": ("我想起了你。", "I thought of you."),
    "吹": ("风在吹。", "The wind is blowing."),
    "确保": ("请确保门关好。", "Please make sure the door is closed."),
    "起诉": ("公司起诉了他。", "The company sued him."),
    "表情": ("她的表情很自然。", "Her expression is natural."),
    "胜利": ("我们取得了胜利。", "We achieved victory."),
    "解雇": ("他被公司解雇了。", "He was fired by the company."),
    "毕业": ("她今年毕业。", "She graduates this year."),
    "打赌": ("我跟你打赌。", "I bet you."),
    "特工": ("他是一名特工。", "He is an agent."),
    "回头": ("他回头看了一眼。", "He looked back once."),
    "去世": ("他去年去世了。", "He passed away last year."),
    "说服": ("我说服了他。", "I persuaded him."),
    "神父": ("神父在教堂里。", "The priest is in the church."),
    "什": ("你为什么迟到？", "Why were you late?"),
    "逃跑": ("小偷逃跑了。", "The thief ran away."),
    "暴力": ("请不要使用暴力。", "Please do not use violence."),
    "汤姆": ("汤姆在家。", "Tom is at home."),
    "笨": ("我真笨。", "I am really foolish."),
    "萨": ("我想吃披萨。", "I want to eat pizza."),
    "被捕": ("小偷被捕了。", "The thief was arrested."),
    "孤独": ("他感到孤独。", "He feels lonely."),
    "惩罚": ("老师惩罚了他。", "The teacher punished him."),
    "怎": ("你怎么知道？", "How do you know?"),
    "杂种": ("“杂种”是粗鲁的话。", "This is a rude word."),
    "咯": ("我先走咯。", "I am leaving first."),
    "佬": ("大佬来了。", "The boss has arrived."),
    "机器人": ("这个机器人会说话。", "This robot can speak."),
    "满足": ("我对结果很满足。", "I am satisfied with the result."),
    "绑": ("请把鞋带绑好。", "Please tie your shoelaces."),
    "早餐": ("我每天吃早餐。", "I eat breakfast every day."),
    "年纪": ("他年纪很大。", "He is quite old."),
    "吃惊": ("这件事让我吃惊。", "This matter surprised me."),
    "指望": ("别指望别人。", "Don't count on others."),
    "感染": ("伤口感染了。", "The wound got infected."),
    "抛弃": ("不要抛弃希望。", "Do not abandon hope."),
    "揍": ("他被揍了一顿。", "He got beaten up."),
    "女友": ("我女友在北京。", "My girlfriend is in Beijing."),
    "大麻": ("大麻在很多地方受管制。", "Cannabis is regulated in many places."),
    "某人": ("某人打电话给你。", "Someone called you."),
    "机构": ("这个机构很有名。", "This organization is well known."),
    "聊聊": ("我们聊聊吧。", "Let's chat."),
    "放心": ("你可以放心。", "You can relax."),
    "尊敬": ("我尊敬老师。", "I respect teachers."),
    "镜头": ("这个镜头很清楚。", "This shot is clear."),
    "联盟": ("他们加入了联盟。", "They joined the alliance."),
    "审判": ("审判明天开始。", "The trial starts tomorrow."),
    "之外": ("除此之外，我没话说。", "Apart from this, I have nothing to say."),
    "放手": ("请放手。", "Please let go."),
    "娶": ("他想娶她。", "He wants to marry her."),
    "保密": ("请为我保密。", "Please keep this secret for me."),
    "加州": ("加州天气很好。", "The weather in California is good."),
    "迪": ("迪士尼很有名。", "Disney is famous."),
    "恋": ("他恋爱了。", "He fell in love."),
    "混乱": ("现场很混乱。", "The scene was chaotic."),
    "爵士": ("我喜欢爵士音乐。", "I like jazz music."),
    "名人": ("他是名人。", "He is famous."),
    "剪": ("请剪短一点。", "Please cut it a little shorter."),
    "人家": ("人家不想去。", "They don't want to go."),
    "爆": ("气球爆了。", "The balloon burst."),
    "监控": ("这里有监控。", "There is surveillance here."),
    "出局": ("他被淘汰出局。", "He was eliminated."),
    "姿势": ("这个姿势很舒服。", "This posture is comfortable."),
    "瞎": ("别瞎说。", "Don't talk nonsense."),
    "汤": ("我想喝汤。", "I want to drink soup."),
    "丽": ("她很美丽。", "She is beautiful."),
    "一路": ("一路顺风。", "Have a safe trip."),
    "打扮": ("她打扮得很漂亮。", "She dressed up beautifully."),
    "起码": ("起码要十分钟。", "It will take at least ten minutes."),
    "玛丽": ("玛丽在家。", "Mary is at home."),
    "地板": ("地板很干净。", "The floor is clean."),
    "骑士": ("他是一名骑士。", "He is a knight."),
    "加拿大": ("我住在加拿大。", "I live in Canada."),
    "坏人": ("他不是坏人。", "He is not a bad person."),
    "发型": ("她的发型很好看。", "Her hairstyle looks good."),
    "敬": ("我敬你一杯。", "I raise a glass to you."),
    "高级": ("这家酒店很高级。", "This hotel is high-end."),
    "后果": ("你要承担后果。", "You must accept the consequences."),
    "拨": ("请拨这个号码。", "Please dial this number."),
    "交往": ("他们交往很久了。", "They have been dating for a long time."),
    "捡": ("他捡起了书。", "He picked up the book."),
    "电子": ("这是电子书。", "This is an e-book."),
    "告": ("请告诉我。", "Please tell me."),
    "割": ("他割破了手。", "He cut his hand."),
    "掌": ("手掌很疼。", "My palm hurts."),
    "蹲": ("他蹲在地上。", "He squatted on the ground."),
    "豁免": ("他获得了豁免。", "He received an exemption."),
    "当事人": ("当事人同意了。", "The party involved agreed."),
    "背景": ("他的背景很复杂。", "His background is complicated."),
    "绝望": ("他感到绝望。", "He feels hopeless."),
    "参议员": ("参议员发表了讲话。", "The senator gave a speech."),
    "凶器": ("警方找到了凶器。", "The police found the weapon."),
    "意味": ("这意味着什么？", "What does this mean?"),
    "艺术家": ("她是艺术家。", "She is an artist."),
    "欧": ("欧洲很远。", "Europe is far away."),
    "技巧": ("这个技巧很有用。", "This technique is useful."),
    "街区": ("这个街区很安静。", "This neighborhood is quiet."),
    "忠诚": ("他对朋友很忠诚。", "He is loyal to his friends."),
    "体内": ("药物留在体内。", "The medicine remains in the body."),
    "掩护": ("请掩护我。", "Please cover me."),
    "承担": ("你要承担责任。", "You must take responsibility."),
    "缺": ("他今天缺席。", "He is absent today."),
    "际": ("国际会议开始了。", "The international meeting has started."),
    "介": ("我来介绍一下。", "Let me introduce it."),
    "旦": ("元旦是节日。", "New Year's Day is a holiday."),
    "杂": ("这里资料很杂。", "The materials here are mixed."),
    "忆": ("我记忆力很好。", "I have a good memory."),
    "档": ("请保存文档。", "Please save the document."),
    "态": ("态度很重要。", "Attitude is important."),
    "毕": ("他毕业了。", "He graduated."),
    "稣": ("耶稣是宗教人物。", "Jesus is a religious figure."),
    "磨": ("我磨了一杯咖啡。", "I ground coffee for a cup."),
    "姆": ("汤姆来了。", "Tom has arrived."),
    "惩": ("老师惩罚了他。", "The teacher punished him."),
    "纪": ("这是二十一世纪。", "This is the twenty-first century."),
    "染": ("她染了头发。", "She dyed her hair."),
    "肤": ("他的皮肤很好。", "His skin is good."),
    "阁": ("阁楼很小。", "The attic is small."),
    "玛": ("玛丽在家。", "Mary is at home."),
    "渴": ("我不渴。", "I am not thirsty."),
    "挥": ("她挥了挥手。", "She waved her hand."),
    "疾": ("他有疾病。", "He has an illness."),
    "豁": ("他获得了豁免。", "He received an exemption."),
    "访": ("我拜访老师。", "I visited my teacher."),
    "誉": ("他的信誉很好。", "His reputation is good."),
    "槟": ("我喝了一杯香槟。", "I drank a glass of champagne."),
    "刑": ("他被判刑。", "He was sentenced."),
    "弗兰克": ("弗兰克在家。", "Frank is at home."),
    "列": ("请列出名单。", "Please list the names."),
    "诉": ("请告诉我真相。", "Please tell me the truth."),
    "姆": ("保姆来了。", "The nanny has arrived."),
    "玛": ("玛瑙很漂亮。", "Agate is beautiful."),
    "陛": ("陛下在大厅里。", "His Majesty is in the hall."),
    "尉": ("他是一名上尉。", "He is a captain."),
    "茜": ("她穿了一件茜色外套。", "She wore a dark red coat."),
    "汀": ("小船停在河边的沙汀上。", "The small boat stopped on the sandbar by the river."),
    "坎": ("门口有一道小坎。", "There is a small threshold at the doorway."),
    "肾": ("医生说他的肾需要检查。", "The doctor said his kidneys need to be checked."),
}


SENTENCE_PINYIN_OVERRIDES: dict[str, str] = {
    "你说得对。": "ni3 shuo1 de5 dui4。",
    "他跑得很快。": "ta1 pao3 de5 hen3 kuai4。",
    "我认为你说得对。": "wo3 ren4 wei2 ni3 shuo1 de5 dui4。",
    "你做得很棒。": "ni3 zuo4 de5 hen3 bang4。",
    "他慢慢地走。": "ta1 man4 man4 de5 zou3。",
    "这种菜很好吃。": "zhe4 zhong3 cai4 hen3 hao3 chi1。",
    "这条路很长。": "zhe4 tiao2 lu4 hen3 chang2。",
    "她跳得很高。": "ta1 tiao4 de5 hen3 gao1。",
    "那匹马跑得很快。": "na4 pi3 ma3 pao3 de5 hen3 kuai4。",
    "她教我中文。": "ta1 jiao1 wo3 zhong1 wen2。",
    "耶，我赢了！": "ye5，wo3 ying2 le5！",
}
