from __future__ import annotations

import json
import subprocess
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"
RAW_BASE_URL = "https://raw.githubusercontent.com/meijer1973/chinese-anki-graded-readers/main/"

SKIPPED_DIRS = {
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "downloads",
    "SUBTLEX-CH-CHR",
    "SUBTLEX-CH-WF",
}


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def git_paths() -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    )
    paths = []
    for raw in result.stdout.splitlines():
        path = raw.strip()
        if not path:
            continue
        if any(part in SKIPPED_DIRS for part in Path(path).parts):
            continue
        if Path(path).is_absolute():
            continue
        paths.append(path.replace("\\", "/"))
    return sorted(set(paths))


def category_for(path: str) -> str:
    if path in {"AGENTS.md", "README.md", "AGENT_GITHUB_ENTRY.md", "RESEARCH_AGENT_MAP.md", "RESEARCH_AGENT_PROMPT.md", "repo_manifest.json"}:
        return "maps/prompts"
    if path.startswith(".agents/") or path.startswith(".codex/"):
        return "agents/skills"
    if path.startswith("docs/"):
        return "docs"
    if path.startswith("scripts/") or path.endswith(".py"):
        return "scripts"
    if path.startswith("tests/"):
        return "tests"
    if path.startswith("data/"):
        return "data"
    if path.startswith("anki/"):
        return "anki"
    if path.startswith("configs/"):
        return "configs"
    if path.startswith("adaptations/"):
        return "adaptations"
    if path.startswith("manuscripts/"):
        return "manuscripts"
    if path.startswith("reports/"):
        return "reports"
    if path.startswith("series/"):
        return "series"
    return "root"


def write_github_agent_index(paths: list[str]) -> None:
    grouped: dict[str, list[str]] = defaultdict(list)
    for path in paths:
        grouped[category_for(path)].append(path)

    lines = [
        "# GitHub Agent File Index - Chinese Anki And Graded Readers",
        "",
        f"Generated: {utc_now()}",
        "",
        "Purpose: lightweight orientation for agents browsing through GitHub. This inventory lists git-trackable files by repository surface.",
        "",
        f"Repository: `https://github.com/meijer1973/chinese-anki-graded-readers`",
        f"Raw base URL: `{RAW_BASE_URL}`",
        f"Files indexed: {len(paths)}",
        "",
        "Skipped directories: " + ", ".join(f"`{item}`" for item in sorted(SKIPPED_DIRS)),
        "",
    ]

    order = [
        "maps/prompts",
        "agents/skills",
        "docs",
        "scripts",
        "tests",
        "configs",
        "data",
        "anki",
        "adaptations",
        "manuscripts",
        "reports",
        "series",
        "root",
    ]
    for category in order:
        items = grouped.get(category, [])
        if not items:
            continue
        lines.extend([f"## {category}", "", f"Count: {len(items)}", ""])
        lines.extend(f"- {item}" for item in items)
        lines.append("")

    (REPORTS / "github-agent-index.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_url_index(paths: list[str]) -> None:
    priority = [
        "RESEARCH_AGENT_MAP.md",
        "RESEARCH_AGENT_PROMPT.md",
        "AGENT_GITHUB_ENTRY.md",
        "AGENTS.md",
        "README.md",
        "repo_manifest.json",
        "reports/github-agent-index.md",
        "docs/novel-generation.md",
        "docs/adaptation-workflow.md",
        "docs/creative-preflight.md",
        "docs/style-bank-controlled-chinese.md",
        "docs/stretch-vocabulary.md",
        "docs/anki-integration.md",
        "docs/quality-review.md",
        "docs/series-memory.md",
        "scripts/check_series_memory_update.py",
        "configs/novel_generation.default.json",
        "data/known_words.metadata.json",
        "data/known_words.txt",
        "anki/stretch_word_candidates.tsv",
        "manuscripts/shanghai-rain-ticket/vocabulary_report.json",
        "manuscripts/shanghai-rain-ticket/quality/quality_gate_summary.json",
    ]
    ordered = []
    seen = set()
    for path in priority + paths:
        if path in paths and path not in seen:
            ordered.append(path)
            seen.add(path)

    lines = [
        "# URL Index",
        "",
        "Single-fetch entry point for external research agents that need literal raw GitHub URLs in context. Generated by `scripts/build_agent_index.py`. Do not hand-edit.",
        "",
        "## Key Entry Points",
        "",
    ]
    for path in ordered[: len(priority)]:
        lines.append(f"- {RAW_BASE_URL}{path}")

    lines.extend(["", "## All Indexed Files", ""])
    for path in ordered:
        lines.append(f"- {RAW_BASE_URL}{path}")

    (REPORTS / "url-index.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_machine_index(paths: list[str]) -> None:
    payload = {
        "schema_version": 1,
        "generated_at": utc_now(),
        "repository": "meijer1973/chinese-anki-graded-readers",
        "raw_base_url": RAW_BASE_URL,
        "file_count": len(paths),
        "files": [{"path": path, "raw_url": f"{RAW_BASE_URL}{path}", "category": category_for(path)} for path in paths],
    }
    (REPORTS / "github-agent-index.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    REPORTS.mkdir(exist_ok=True)
    paths = git_paths()
    write_github_agent_index(paths)
    write_url_index(paths)
    write_machine_index(paths)
    print(f"indexed_files={len(paths)}")
    print("wrote reports/github-agent-index.md")
    print("wrote reports/github-agent-index.json")
    print("wrote reports/url-index.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
